name: My First GitHub Action

on: [push]

jobs:
  build:
    runs-on: self-hosted  # Run the job on a self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Update to v3
      with:
        python-version: '3.7'  # Using Python 3.8 instead of 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        python -m pytest addition.py
