name: My First GitHub Action

on: [push]

jobs:
  build:
    runs-on: self-hosted  # Run the job on a self-hosted runner

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python (specify a version, e.g., 3.9)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can specify the version you want

    # Install dependencies (pip and pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run tests with pytest
    - name: Run tests
      run: |
        python -m pytest addition.py
